
GET http://localhost:3003

###

GET http://localhost:3003/api
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2VjcmFjayIsIm5hbWUiOiJNaWtlIENyYWNrIiwicGFzc3dvcmQiOiIkMmIkMDUkUDA3UmpkSGlDMEFqTGtNOHR1aXc5ZVkwdHlhMUpmRkJuLy82MDJJS3hmQ3RrVzBKZENrQmUiLCJpYXQiOjE3MDAwODY3NzgsImV4cCI6MTcwMDk1MDc3OH0.bZL-Xsa2WRKcw5cAPqFYwFXH9JCdr3HB5vqqop3XFRA

###

// BLOGS

// get blogs
GET http://localhost:3003/api/blogs
###

// get blogs with author username
GET http://localhost:3003/api/mix/blogs

###

// post a blog
POST http://localhost:3003/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5pY29sYXMgdGFnbGlhIiwibmFtZSI6Ik5pY29sYXMgVGFnaWFmaWNvIiwicGFzc3dvcmQiOiIkMmIkMDUkSWVTYTZoZmJNaW5lUHhsVFNEUnJOZVJsUk1JbEVqalNoQ05yM3BXTGZSUGNVOGNPU0xHbk8iLCJpYXQiOjE3MDAxMDU0NTAsImV4cCI6MTcwMDk2OTQ1MH0.CciNNivKxMCMY9teTMoSBFUNeiHvIHiE-hEHwly-ZYI
Content-Type: application/json

{
  "title": "Messi: Overall",
  "url": "hhtp://www.mipaginaweb.com.ar",
  "likes": 178
}

###

// remove blog
DELETE http://localhost:3003/api/blogs/6555a2c322aa0ed4ed2b3650
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2VjcmFjayIsIm5hbWUiOiJNaWtlIENyYWNrIiwicGFzc3dvcmQiOiIkMmIkMDUkUDA3UmpkSGlDMEFqTGtNOHR1aXc5ZVkwdHlhMUpmRkJuLy82MDJJS3hmQ3RrVzBKZENrQmUiLCJpYXQiOjE3MDAwODY3NzgsImV4cCI6MTcwMDk1MDc3OH0.bZL-Xsa2WRKcw5cAPqFYwFXH9JCdr3HB5vqqop3XFRA

###

// modify blog likes count
PATCH http://localhost:3003/api/blogs/setlikes/6555a32a22aa0ed4ed2b3654?likes=154
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWljaGFlbCBNYXNpIiwidXNlcm5hbWUiOiJNTWFzaSIsImhhc2hlZFBhc3N3b3JkIjoiJDJiJDA1JDNWaVJHQkNvOFgzdXJBQU5ZLk5DU3VnMXl2OC5pUWdUazVvajVldW5FY0lVdXZBQjQyemxpIiwiaWF0IjoxNzAwMzQ1MDE0LCJleHAiOjE3MDEyMDkwMTR9.YRx9CQwp_PFpT6yj6AgkyQEsDJ83AT4f6HXeza1rDk8
### 

// comment (anonym)

POST http://localhost:3003/api/blogs/comment/656cbc5273013dbf841d5a18
Content-Type: application/json

{
  "commentBody": "very interesting!"
}

###

// USERS

// get all users
GET http://localhost:3003/api/users

###

// signin
POST http://localhost:3003/api/users/signin
Content-Type: application/json

{
  "username": "Richard Harrison",
  "name": "Michael Masi",
  "password": "pawnstarts"
}

###

// login
POST http://localhost:3003/api/users/login
Content-Type: application/json

{
  "username": "Richard Harrison",
  "password": "uzumymw"
}

###

GET http://localhost:3003/api/users/blogs

###

// TESTS

GET http://localhost:3003/testUtils/resetDB